
version: 2

sources:
  - name: ACCEL_ABCNEW_RAW         # dbt will reference this as 'source("accel_abcnew_raw", "package")'
    database: DEV
    schema: ACCEL_ABCNEW_RAW
    tables:
      - name: package
        description: "Raw source table containing package data"

